# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "024a74d2371b7b7c90490da4582eb8c1"
name = "sopifixstore"
handle = "sopifixstore"
application_url = "https://phil-proceed-merchandise-anger.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://phil-proceed-merchandise-anger.trycloudflare.com/auth/callback",
  "https://phil-proceed-merchandise-anger.trycloudflare.com/auth/shopify/callback",
  "https://phil-proceed-merchandise-anger.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
